sudo: require
services:
  - docker
before_install:
  - docker pull node:8-onbuild
install:
  - docker build -t probot-hello .
script:
    - docker run --rm probot-hello npm run test
    - docker run --rm probot-hello npm run lint

deploy:
  provider: heroku
  api-key:
    secure: IBjO25cQDcUiwXxAp+pyqxNZnuVQCFD3qHlsj6jsFyHccJ7798bxnIGEGw+Itwm+UUzbQXTL6ENBTNIyCFf/rK522VruKzylKKZlSozSfzZTFRXDZVgi0DwqRovA2blCm9rKjv8qNWlErMyZpMHLXYejAqS5NseOy4w5wif6WcHGCvd8YGVCjjGK/ZFk/xGZnrV+ES4Dv0d5gq47G42tiRd3nZybUndZLQuTX02+1r5P81CUbn6rxDwIuDyM3gN0wm82linLI/PPUNGzlON6iMtCD30Xk/aN9wwCjTi8O69WSD8/a+xuxiiwCwUaPLAW8dsobRT5LXLyyEm8UW2j/bmb0RocWF7CwCqv1mG+qq3IDaukzfY+Cwdt2NEHSVPeMqLuW0YeTLVlWffJpvnnQqXHSW3jAWa+muO/eL+SIJcKQYkHE5vMQ7TLqKAJMrDbEPJzI24w/TotjofLNnDdK3uO1Ox5bIZXsKrg7KNp1iRlyrdb9N6vVHzHqFj9SsiH3KFvErhafZ8WIU2pnHfl/q43UuvyOAZVDHUdWxuOy6sgVWgBqV8ejOtQbWlRJnn5TtuOLfOyZqWHFaf4twLrTi9b7VGsffUWPU7wWauFakjRUVERbSKUPyCfSEpaH9qNwAIhYW9+74HvDVRQIqC9AFT5mTjuQz0Q2qKGeRc9nwo=
  on: heroku_production
  app: probot-noor54
